### ISSUE TITLE
`sudo -u myself sudo true` hangs

### ISSUE THREAD

**Issue by japaric** [memorysafety/sudo-rs#388]
relevant test 

https://github.com/memorysafety/sudo-rs/blob/a01513b2a8c0c20cd8600f9009f2dc9bb5e6bec4/test-framework/sudo-compliance-tests/src/timestamp.rs#L413-L427

``` console
ferris@8eee38885c5f:/$ echo my-password | sudo -S true
[Sudo: authenticate] Password:

ferris@8eee38885c5f:/$ sudo true

ferris@8eee38885c5f:/$ sudo -u ferris env SUDO_RS_IS_UNSTABLE='I accept that my system may break unexpectedly' sudo true
```

the last command produces no output and makes sudo-rs hang. ogsudo returns immediately with exit code 0 and without prompting for a password

credential caching seems to be unrelated. this also hangs:

``` console
ferris@8eee38885c5f:/$ sudo -K

ferris@8eee38885c5f:/$ sudo -u ferris env SUDO_RS_IS_UNSTABLE='I accept that my system may break unexpectedly' sudo true
```

**Comment by pvdrz** [comment]
I cannot reproduce it either. I think this was fixed during the `exec` spring cleaning

**Comment by japaric** [comment]
the test still fails otherwise CI would have told us otherwise. if I change the spawn + try_wait back to `output.assert_success` I see the test hang.

> the second sudo just asks me for a password, which makes sense since it's in a different tty.

I think that's part of the problem. ogsudo does not prompt for a password

ogsudo
``` console
ferris@45153bdd4cf8:/tmp$ sh -c 'echo ferris | sudo -S true; sudo -u ferris env SUDO_RS_IS_UNSTABLE="I accept that my system may break unexpectedly" sudo true'
ferris@45153bdd4cf8:/tmp$ echo $?
0
```

sudo-rs
``` console
ferris@51ffd177eca4:/tmp$ sh -c 'echo ferris | sudo -S true; sudo -u ferris env SUDO_RS_IS_UNSTABLE="I accept that my system may break unexpectedly" sudo true'
[sudo: authenticate] Password:
```

**Comment by squell** [comment]
Perhaps this is due to sudo-rs using `use_pty` by default?

**Comment by squell** [comment]
Confirmed. Adding `Defaults !use_pty` makes us pass this test, adding `Defaults use_pty` makes original sudo fail the test.
